CC=gcc
CFLAGS=-I.

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
all:
	g++ -fPIC -Wall -c fmu.cpp
	g++ -fPIC -Wall -c skeleton.cpp
	g++ -fPIC -shared -o {{name}}.so skeleton.o fmu.o -Wl,-rpath,. -lwebsockets -lssl -lcrypto
	rm -rf sources
	rm -rf binaries
	mkdir sources
	mkdir  binaries
	mkdir binaries/linux64
	cp fmu.h sources
	cp FmuGUID.h sources
	cp fmu.cpp sources
	cp skeleton.cpp sources
	mv {{name}}.so binaries/linux64/
	cp /usr/local/lib/libwebsockets.so.11 binaries/linux64/
	zip -r {{name}}.fmu modelDescription.xml binaries/ resources/ sources/
	rm -rf sources
	rm -rf binaries

run3:
	./fmuCheck.linux64 -h 1E-03 {{name}}.fmu
run4:
	./fmuCheck.linux64 -h 1E-04 {{name}}.fmu

clean:
	rm -rf  {{name}}.o fmu.o skeleton.o
