CC=gcc
CFLAGS=-I.

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS)
all:
	gcc -fPIC -Wall -c fmu.c
	gcc -fPIC -Wall -c skeleton.c
	gcc -fPIC -Wall -c misraC/{{name}}.c
	gcc -shared -o {{name}}.so skeleton.o fmu.o {{name}}.o -lwebsockets -lssl -lcrypto
	rm -rf sources
	mkdir sources
	cp fmu.h sources
	cp fmu.c sources
	cp skeleton.c sources
	cp misraC/* sources
	cp -r fmi sources
	mv {{name}}.so binaries/linux64/
	zip -r {{name}}.fmu modelDescription.xml binaries/ resources/ sources/

run:
	./fmuCheck.linux64 -h 1E-01 {{name}}.fmu
run1:
	./fmuCheck.linux64 -h 1E-02 {{name}}.fmu

clean:
	rm -rf  {{name}}.o fmu.o skeleton.o
